from sqlalchemy import Column, Date, DateTime, CHAR, DECIMAL, TEXT
from config.dbconnection import Base

class Cartera(Base):
    __tablename__ = 'CARTERA'

    FACTURA = Column(CHAR(12), primary_key=True)
    EMPRESA = Column(CHAR(2))
    TIPO = Column(CHAR(2))
    NOMTIPO = Column(CHAR(10), default='')
    TIPRECARGO = Column(CHAR(10), default='')
    NOMTIPRECAR = Column(CHAR(25), default='')
    PLAZO = Column(DECIMAL(4, 0), default='')
    CLIENTE = Column(CHAR(12), default='')
    CEDULA = Column(CHAR(12), default='')
    CLASIFICAC = Column(CHAR(1), default='')
    ZONA = Column(CHAR(2), default='')
    VENDEDOR = Column(CHAR(12), default='')
    CIUDAD = Column(CHAR(5), default='')
    PLACA = Column(CHAR(12), default='')
    UNIDAD = Column(CHAR(5), default='')
    PROPI_IDEN = Column(CHAR(12), default='')
    FEC_ENTREG = Column(Date, default='')
    MORA = Column(DECIMAL(4, 0), default='')
    VALOR = Column(DECIMAL(12, 2), default='')
    FECHA = Column(Date, default='')
    FEC_FACTU = Column(Date, default='')
    DOC_FACTU = Column(CHAR(12), default='')
    CAN_FACTU = Column(DECIMAL(4, 0), default='')
    ABONOS = Column(DECIMAL(12, 2), default='')
    FEC_ABONO = Column(Date, default='')
    DOC_ABONO = Column(CHAR(12), default='')
    CAN_ABONO = Column(DECIMAL(4, 0), default='')
    INTERESES = Column(DECIMAL(12, 2), default='')
    FEC_INTER = Column(Date, default='')
    DOC_INTER = Column(CHAR(12), default='')
    CAN_INTER = Column(DECIMAL(4, 0), default='')
    DESCUENTOS = Column(DECIMAL(12, 2), default='')
    FEC_DESCU = Column(Date, default='')
    DOC_DESCU = Column(CHAR(12), default='')
    CAN_DESCU = Column(DECIMAL(4, 0), default='')
    N_DEB = Column(DECIMAL(12, 2), default='')
    FEC_NDEB = Column(Date, default='')
    DOC_NDEB = Column(CHAR(12), default='')
    CAN_NDEB = Column(DECIMAL(4, 0), default='')
    N_CRE = Column(DECIMAL(12, 2), default='')
    FEC_NCRE = Column(Date, default='')
    DOC_NCRE = Column(CHAR(12), default='')
    CAN_NCRE = Column(DECIMAL(4, 0), default='')
    DETALLE = Column(TEXT, default='')
    DOC_CRUCE = Column(CHAR(8), default='')
    VLR_CRUCE = Column(DECIMAL(12, 2), default='')
    FEC_CRUCE = Column(Date, default='')
    FEC_DESDE = Column(Date, default='')
    FEC_HASTA = Column(Date, default='')
    FACTRELA = Column(CHAR(10), default='')
    CRUCE = Column(DECIMAL(1, 0), default='')
    SALDO = Column(DECIMAL(12, 2), default='')
    FEC_CUADRE = Column(Date, default='')
    FEC_DOC = Column(CHAR(8), default='')
    SALDO00 = Column(DECIMAL(12, 2), default='')
    DEB01 = Column(DECIMAL(12, 2), default='')
    CRE01 = Column(DECIMAL(12, 2), default='')
    SALDO01 = Column(DECIMAL(12, 2), default='')
    DEB02 = Column(DECIMAL(12, 2), default='')
    CRE02 = Column(DECIMAL(12, 2), default='')
    SALDO02 = Column(DECIMAL(12, 2), default='')
    DEB03 = Column(DECIMAL(12, 2), default='')
    CRE03 = Column(DECIMAL(12, 2), default='')
    SALDO03 = Column(DECIMAL(12, 2), default='')
    DEB04 = Column(DECIMAL(12, 2), default='')
    CRE04 = Column(DECIMAL(12, 2), default='')
    SALDO04 = Column(DECIMAL(12, 2), default='')
    DEB05 = Column(DECIMAL(12, 2), default='')
    CRE05 = Column(DECIMAL(12, 2), default='')
    SALDO05 = Column(DECIMAL(12, 2), default='')
    DEB06 = Column(DECIMAL(12, 2), default='')
    CRE06 = Column(DECIMAL(12, 2), default='')
    SALDO06 = Column(DECIMAL(12, 2), default='')
    DEB07 = Column(DECIMAL(12, 2), default='')
    CRE07 = Column(DECIMAL(12, 2), default='')
    SALDO07 = Column(DECIMAL(12, 2), default='')
    DEB08 = Column(DECIMAL(12, 2), default='')
    CRE08 = Column(DECIMAL(12, 2), default='')
    SALDO08 = Column(DECIMAL(12, 2), default='')
    DEB09 = Column(DECIMAL(12, 2), default='')
    CRE09 = Column(DECIMAL(12, 2), default='')
    SALDO09 = Column(DECIMAL(12, 2), default='')
    DEB10 = Column(DECIMAL(12, 2), default='')
    CRE10 = Column(DECIMAL(12, 2), default='')
    SALDO10 = Column(DECIMAL(12, 2), default='')
    DEB11 = Column(DECIMAL(12, 2), default='')
    CRE11 = Column(DECIMAL(12, 2), default='')
    SALDO11 = Column(DECIMAL(12, 2), default='')
    DEB12 = Column(DECIMAL(12, 2), default='')
    CRE12 = Column(DECIMAL(12, 2), default='')
    SALDO12 = Column(DECIMAL(12, 2), default='')
    FEC_DOCUM = Column(CHAR(8), default='')
    FEC_CREADO = Column(Date, default='')
    USU_CREADO = Column(CHAR(8), default='')
    FEC_MODIFI = Column(Date, default='')
    USU_MODIFI = Column(CHAR(8), default='')
    FEC_HABILI = Column(Date, default='')
    USU_HABILI = Column(CHAR(8), default='')
    PROCESO = Column(CHAR(1), default='')
    EX = Column(CHAR(1), default='')
    SEL = Column(CHAR(1), default='')
    PAGO = Column(DECIMAL(1, 0), default='')
