from sqlalchemy import Column, CHAR, VARCHAR, DECIMAL
from config.dbconnection import Base

class Yappy(Base):
    __tablename__ = 'YAPPY'

    EMPRESA = Column(CHAR(2), primary_key=True)
    REFERENCIA = Column(CHAR(25), primary_key=True)
    FECHA = Column(CHAR(10))
    HORA = Column(CHAR(10))
    NOMBRE = Column(CHAR(30))
    CELULAR = Column(CHAR(20))
    COMENTARIO = Column(VARCHAR(50))
    ESTADO = Column(CHAR(30))
    PTO_COBRO = Column(CHAR(20))
    IDENTIFICA = Column(CHAR(20))
    MOTIVOPAGO = Column(CHAR(20))
    SUBTOTAL = Column(DECIMAL(10, 2))
    PROPINA = Column(DECIMAL(10, 2))
    DESCUENTO = Column(DECIMAL(10, 2))
    IMPUESTO = Column(DECIMAL(10, 2))
    CREDITO = Column(DECIMAL(10, 2))
    IDGRUPO = Column(CHAR(1))
    IDCAJA = Column(CHAR(1))
    DEBITO = Column(DECIMAL(10, 2))
    COMISION = Column(DECIMAL(5, 2))
    INSCRIPCIO = Column(DECIMAL(10, 2))
    MULTA = Column(DECIMAL(10, 2))
    PANAPASS = Column(DECIMAL(10, 2))
    SINIESTROS = Column(DECIMAL(10, 2))
    TOTAL = Column(DECIMAL(10, 2))
    UNIDAD = Column(CHAR(8))
    UNIDAD2 = Column(CHAR(8))
    CEDULA = Column(CHAR(12))
    CODIGO = Column(CHAR(12))
    NOMESTADO = Column(CHAR(30))
    TIPO = Column(CHAR(1))
    OBSERVA = Column(CHAR(50))
    SDOMULTAS = Column(DECIMAL(10, 2))
    CARTERA = Column(DECIMAL(10, 2))
    TCRE = Column(DECIMAL(10, 2))
    TSDO = Column(DECIMAL(10, 2))
